-- -- CREATE OR REPLACE FUNCTION NthHighestSalary(N INT) RETURNS TABLE (Salary INT) AS $$
-- -- BEGIN
-- SELECT DISTINCT e.salary
-- from EMployees e
-- order by salary DESC
-- OFFSET N - 1 
-- LIMIT 1;
